### ISSUE TITLE
Make company information configurable

### ISSUE THREAD

**Issue by ArjenMiedema** [mediact/coding-standard-phpstorm#20]
As a developer I want to have my own copyright layout in my files, so that I don't get all files copyrighted by MediaCT.

In the file [`files/fileTemplates/includes/Company Settings.php`](https://github.com/mediact/coding-standard-phpstorm/blob/master/files/fileTemplates/includes/Company%20Settings.php), the settings are set to MediaCT specific settings. These settings should be easy to customize for other companies.

- [x] The company, vendor and website variables for PHPStorm files can be customized

**Comment by leonhelmus** [comment]
@ArjenMiedema I will look into this next week. We will have to chance it aswell so i will let you know once i'm done.

**Comment by leonhelmus** [comment]
@ArjenMiedema  i have looked into it and i dont overwrite files/fileTemplates/includes/Company Settings.php once it has already been added. Please check https://github.com/mediact/coding-standard-phpstorm/blob/fa714001dd6da2a4b6dd504558b5a1301a95c4c4/src/Patcher/TemplateSettingsPatcher.php#L119 and you can confirm.

So when the M2-Settings template has been added it will not be overwritten.

You can change the company settings by going to:
Phpstorm -> file -> settings -> Editor -> File and code templates -> includes -> M2-Settings and change the company name there.

**Comment by leonhelmus** [comment]
@ArjenMiedema  Please confirm if this solved your issue.

**Comment by ArjenMiedema** [comment]
So basically, setting our own templates would do the trick. I think that could work. Thanks!
